INFO 2022-07-28 17:06:13 FaceDetModelLoader.py: 39] Successfully loaded the face detection model!
INFO 2022-07-28 17:06:16 _internal.py: 224] 192.168.3.3 - - [28/Jul/2022 17:06:16] "POST /idCardPhoto/photo/faceImgMatting HTTP/1.1" 200 -
INFO 2022-07-28 17:06:16 _internal.py: 224] 192.168.3.3 - - [28/Jul/2022 17:06:16] "GET /static/page/img/a6d37566c67545a49c193884efd67364_rgba.png HTTP/1.1" 200 -
INFO 2022-07-28 17:07:09 FaceDetModelLoader.py: 21] Start to analyze the face detection model, model path: models, model category: face_detectionï¼Œmodel name: face_detection_1.0
INFO 2022-07-28 17:07:09 BaseModelLoader.py: 39] Successfully parsed the model configuration file meta.json!
INFO 2022-07-28 17:07:09 FaceDetModelLoader.py: 39] Successfully loaded the face detection model!
INFO 2022-07-28 17:07:12 _internal.py: 224] 192.168.3.3 - - [28/Jul/2022 17:07:12] "POST /idCardPhoto/photo/faceImgMatting HTTP/1.1" 200 -
INFO 2022-07-28 17:07:12 _internal.py: 224] 192.168.3.3 - - [28/Jul/2022 17:07:12] "GET /static/page/img/7bf0dc4fd3b8482d9f5732fb1ec1c0a9_rgba.png HTTP/1.1" 200 -
DEBUG 2022-07-28 17:19:16 PngImagePlugin.py: 153] STREAM b'IHDR' 16 13
DEBUG 2022-07-28 17:19:16 PngImagePlugin.py: 153] STREAM b'IDAT' 41 8192
INFO 2022-07-28 17:19:16 _internal.py: 224] 192.168.3.3 - - [28/Jul/2022 17:19:16] "POST /idCardPhoto/photo/imageCompose HTTP/1.1" 200 -
INFO 2022-07-28 17:19:17 _internal.py: 224] 192.168.3.3 - - [28/Jul/2022 17:19:17] "[33mGET /img/7bf0dc4fd3b8482d9f5732fb1ec1c0a9_c.png HTTP/1.1[0m" 404 -
INFO 2022-07-28 17:19:56 _internal.py: 224] 192.168.3.3 - - [28/Jul/2022 17:19:56] "[33mPOST /img/7bf0dc4fd3b8482d9f5732fb1ec1c0a9_c.png HTTP/1.1[0m" 404 -
INFO 2022-07-28 17:20:42 _internal.py: 224]  * Detected change in '/Users/vega/workspace/codes/py_space/working/photo-tools-api/photo_tools_app/service/static_pages.py', reloading
